name: Integration Test

on:
  push:
    branches: [ v0.10 ]
  pull_request:
    branches: [ v0.10 ]

jobs:
  test:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Run integration tests
      run: |
        sudo su <<EOF
        source /etc/profile
        ./integration_test.sh -dbtype=*mysql
        EOF
